#                               #                                                                                                         #
#                               #                                                                                                         #
#                               #                                                                                                         #
#                               ###########################################################################################################
#                               #                                                                                                         #
#                               #   ░█████╗░░█████╗░███╗░░██╗███████╗██╗░██████╗░██╗░░░██╗██████╗░░█████╗░████████╗██╗░█████╗░███╗░░██╗   #
#                               #   ██╔══██╗██╔══██╗████╗░██║██╔════╝██║██╔════╝░██║░░░██║██╔══██╗██╔══██╗╚══██╔══╝██║██╔══██╗████╗░██║   #
#                               #   ██║░░╚═╝██║░░██║██╔██╗██║█████╗░░██║██║░░██╗░██║░░░██║██████╔╝███████║░░░██║░░░██║██║░░██║██╔██╗██║   #
#                               #   ██║░░██╗██║░░██║██║╚████║██╔══╝░░██║██║░░╚██╗██║░░░██║██╔══██╗██╔══██║░░░██║░░░██║██║░░██║██║╚████║   #
#                               #   ╚█████╔╝╚█████╔╝██║░╚███║██║░░░░░██║╚██████╔╝╚██████╔╝██║░░██║██║░░██║░░░██║░░░██║╚█████╔╝██║░╚███║   #
#                               #   ░╚════╝░░╚════╝░╚═╝░░╚══╝╚═╝░░░░░╚═╝░╚═════╝░░╚═════╝░╚═╝░░╚═╝╚═╝░░╚═╝░░░╚═╝░░░╚═╝░╚════╝░╚═╝░░╚══╝   #
#                               #                                                                                                         #
#                               ###########################################################################################################
#
#
#
# Bienvenue dans la configuration FR du plugin ! Vous allez trouver un guide pour configurer le plugin.
# If you are an english speaker, you can load an EN version of this file by running the command '/pds load config'
# À savoir que ce fichier n'est pas pris en compte par le plugin s'il n'est pas nommé "config.yml".


# Défini les 3 items du plugin, la configuration est pareil pour les 3 items
Items:
  BasicDebugStick:
    # Le matériel de l'item (ex : ARROW)
    Material: "BAMBOO"

    # Le nom de l'item
    Name: "#33FFBB&lBASIC DEBUG STICK"

    # Son lore, sa description. Chaque élément de la liste représente une ligne du lore.
    # PH :
    # {durability} : la durabilité du debug-stick (évidemment, uniquement le basic debugstick peut avoir ce PH)
    Lore:
      - ""
      - "&e&lCLIQUE DROIT"
      - " &7&opour éditer les propriétés"
      - ""
      - "&a&lCLIQUE GAUCHE"
      - " &7&opour changer la propriété courante"
      - ""
      - "&c&lSHIFT + CLIQUE DROIT"
      - " &7&opour supprimer les valeurs permanentes"
      - ""
      - "&9&lSHIFT + CLIQUE GAUCHE"
      - " &7&opour voir toutes les propriétés éditables"
      - ""
      - "&aDurabilité restante : &e{durability}"

    # Les enchantements de l'item, purement visuel. Chaque ligne représente un enchantement.
    Enchants:

    # Cacher les enchantements
    HideEnchants: true

    # Cacher les attributs
    HideAttributes: true

    # Cacher les effets de potion
    HidePotionEffets: true

    # Cacher la teinture
    HideDye: true

    # Cacher si le bloc ne peut être placé qu'à un endroit
    HidePlacedOn: true

    # Ajouter le flag 'unbreakable' (purement esthétique)
    IsUnbreakable: false

  InfinityDebugStick:
    Material: "DEAD_BUSH"
    Name: "<s:E60000>&lINFINITE<e:FFD919><s:FFD919> &lDEBUG STICK<e:E60000>"
    Lore:
      - ""
      - "&e&lCLIQUE DROIT"
      - " &7&opour éditer les propriétés"
      - ""
      - "&a&lCLIQUE GAUCHE"
      - " &7&opour changer la propriété courante"
      - ""
      - "&c&lSHIFT + CLIQUE DROIT"
      - " &7&opour supprimer les valeurs permanentes"
      - ""
      - "&9&lSHIFT + CLIQUE GAUCHE"
      - " &7&opour voir toutes les propriétés éditables"
      - ""
      - "&aDurabilité restante : &e∞"


    Enchants:
      - "unbreaking"
    HideEnchants: true
    HideAttributes: true
    HidePotionEffets: true
    HideDye: true
    IsUnbreakable: true
    HideUnbreakable: false
    HidePlacedOn: true

  Inspector:
    Material: "GOLD_INGOT"
    Name: "<s:FF8C19>&lINSPECTOR<e:FF8C19>"
    Lore:
      - ""
      - "&a&lCLIQUE DROIT &7&opour avoir les implémentations"
      - "&c&lCLIQUE GAUCHE &7&opour voir les propriétés"
    Enchants:
      - "unbreaking"

    HideEnchants: false
    HideAttributes: true
    HidePotionEffets: true
    HideDye: true
    IsUnbreakable: true
    HideUnbreakable: false
    HidePlacedOn: true

Settings:
  # Les dégâts de durabilité que le basic debug stick va prendre lorsqu'il va éditer cette propriété.
  # La définition de chaque propriété se trouve dans le fichier properties_fr.
  # Les dégâts peuvent valoir 0, mais ne peuvent pas être négatif.
  Durability:
    ORIENTABLE: 1
    DIRECTIONAL: 1
    ROTATABLE: 1
    SLAB: 1
    BISECTED: 1
    SHAPE_STAIRS: 1
    SHAPE_RAIL: 1
    PERSISTENT: 3
    MULTIPLE_FACING: 1
    LIGHTABLE: 5
    REDSTONE_WIRE: 2
    WATER_LOGGED: 3
    ANALOGUE_POWERABLE: 10
    POWERABLE: 10
    AGEABLE: 20
    STAGE: 10
    HONEY_LEVEL: 5
    WALL: 1
    SNOWABLE: 3
    DISTANCE: 1
    LAYERS: 1
    BAMBOO_LEAVES: 2
    TILT: 5
    EGGS: 50
    HATCH: 20
    SIGNAL_FIRE: 5
    ATTACHABLE: 5
    EXTENDABLE: 10
    HANGABLE: 5
    CAKE: 5
    BERRY: 10
    CONDITIONAL: 10
    OPENABLE: 1
    END_PORTAL_FRAME: 5
    FACE_ATTACHABLE: 3
    FARMLAND: 3
    GATE: 3
    LEVELLED: 10
    THICKNESS: 5
    VERTICAL_DIRECTION: 1
    DELAY: 1
    LOCKED: 2
    CHARGES: 5
    BLOOM: 10
    PHASE: 3
    SUMMON: 10
    SHRIEKING: 1
    PICKLES: 10
    DISARMED: 3
    BRUSHABLE: 3
    OCCUPIED_SLOT: 5
    PETALS: 20


  # Lorsqu'un joueur n'a pas la permission d'éditer une propriété, faut-il cacher ou non la propriété
  # au joueur ?
  HideNoPermProperty: true

  BlackList:
    # Liste de matériaux qui ne sont pas éditables sans la permission 'pds.bypass.blacklist.material'
    Material:
      - "CHEST"

    # Liste des mondes qui ne peuvent pas être édité sans la permission 'pds.bypass.blacklist.world'
    World:
      - "world_the_end"


  # Avertit le joueur lorsque son basic debug stick va casser
  # La configuration de ce message se fait dans le fichier 'messages.yml' à 'OnUse' -> 'WarnBreakMessage'
  WarnPlayerWhenBreaking:
    Enable: true

    # Send the message one time (true) or each time the player will use the debug stick and his durability
    # Envoi le message à chaque fois que le joueur va utiliser basic son debug stick et que la durabilité est en
    # dessous de celle paramétrée.
    SendOnce: false

    # La durabilité du basic debug stick pour que le joueur soit averti
    Durability: 5


Log:
  # Le format du log
  # Si aucune valeur n'est définie et que les logs sont actifs, le plugin va loger ce message par défaut :
  # "{player} edited the property {property_name} from {old_value} to {value} of the block at {block_loc_x} {block_loc_y} {block_loc_z}"
  # Exemple de log avec ce format :
  # [01:04:27 INFO]: [DebugStick] Machigan edited the property bisected from bottom to top of the block at 39 -60 3 in world
  #
  # PH : fonctionne de la même manière que dans le fichier 'messages.yml'
  # tous les place holder liés à un joueur en ligne sont utilisables ici (et ceux pas liés aux joueurs)
  # {property} : la propriété que le joueur a édité
  # {value} : la nouvelle valeur de la propriété
  # {old_value} : l'ancienne valeur de la propriété
  # {block} : le bloc que le joueur a édité
  # {year} : l'année de l'édition
  # {month} : le mois (nombre) de l'édition
  # {day} : le jour du mois (nombre) de l'édition
  # {hour} : l'heure de l'édition
  # {minute} : la minute de l'édition
  # {second} : la seconde de l'édition
  # {player} : le nom du joueur (si vous utilisez PlaceHolderAPI, ce PH n'est pas utile -> %player_name%)
  Format: "{player} edited the property {property_name} from {old_value} to {value} of the block at {block_loc_x} {block_loc_y} {block_loc_z} in {block_loc_world}"

  # Activer les logs dans la console ?
  Console: false



# Créer les recettes de craft pour les items du plugin
# To create a recipe, you have to create a new field in the recipes section and name
# Pour créer une recette vous devez créer une nouvelle section et la nommer comme vous le voulez
# Dans cette nouvelle section, il y a 3 sections à créer (avec des noms pré-définis) :
# 'Item' : parmi "BASIC", "INFINITY" ou "INSPECTOR"
# 'Durability' : la durabilité que le debug stick va avoir, cette section n'est pas utile si l'item n'est pas "BASIC"
# 'Craft' : Représente les slots de la table de craft ainsi :
#
#   / / / / / / /
#   / 1 / 2 / 3 /    / / / / / / / / /
#   / 4 / 5 / 6 / -> /the debug stick/
#   / 7 / 8 / 9 /    / / / / / / / / /
#   / / / / / / /
#
# You must not use all slot but each slot that you want to use, represent a material
# here is for you 2 examples of recipes :
Recipes:
  basic:
    Item: "BASIC"
    Durability: 1000
    Craft:
      2: "DIAMOND"
      5: "BLAZE_ROD"
      8: "BLAZE_ROD"
  infinity:
    Item: "INFINITY"
    Craft:
      1: "BEACON"
      2: "NETHERITE_BLOCK"
      3: "BEACON"
      5: "BLAZE_ROD"
      8: "BLAZE_ROD"